AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyConnectInstance:
    Type: "AWS::Connect::Instance"
    Properties:
      Attributes:
           InboundCalls: true
           OutboundCalls: true
      IdentityManagementType: "CONNECT_MANAGED"
      InstanceAlias: "testKapil"